# userver

# Отключаем сборку тестов
set(USERVER_FEATURE_JEMALLOC OFF)
set(USERVER_FEATURE_MONGODB OFF)
set(USERVER_FEATURE_POSTGRESQL OFF)
set(USERVER_FEATURE_PATCH_LIBPQ OFF)
set(USERVER_FEATURE_REDIS OFF)
set(USERVER_FEATURE_GRPC OFF)
set(USERVER_FEATURE_CLICKHOUSE OFF)
set(USERVER_FEATURE_RABBITMQ OFF)
set(USERVER_FEATURE_UTEST OFF)
set(USERVER_FEATURE_TESTSUITE OFF)

add_subdirectory(${THIRD_PARTY_DIR}/userver)
userver_setup_environment()
