components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000

        # Storage
        storage-wrapper:
            database: $storage-database
            host: $storage-host
            port: $storage-port
            username: $storage-username
            password: $storage-password

        # Static content
        fs-cache-main:
            dir: /mnt/c/Users/october/Desktop/dev/python_projects/log_analysis_web/log_analysis_web/site

        handler-static:
            path: /*
            method: GET
            fs-cache-component: fs-cache-main
            task_processor: main-task-processor

        # Anomaly Logs
        anomaly-logs-get:
            path: /anomaly_logs
            method: GET
            task_processor: main-task-processor

        anomaly-logs-update-cluster-id:
            path: /anomaly_logs/update_cluster_id
            method: POST
            task_processor: main-task-processor

        # Logs Clusters
        logs-clusters-create:
            path: /logs_clusters
            method: POST
            task_processor: main-task-processor

        logs-clusters-get:
            path: /logs_clusters
            method: GET
            task_processor: main-task-processor

        # Statistics
        statistics-get:
            path: /statistics
            method: GET
            task_processor: main-task-processor
