worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: false

server-port: 8080

# Storage
storage-database: log_analysis
storage-host: localhost
storage-port: 5432
storage-username: postgres
storage-password: postgres

# Static content
site-directory: site
